server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: http://localhost:8081 # Target service URL
          predicates:
            - Path=/customers/** # Incoming URL pattern
        - id: reservation_route
          uri: http://localhost:8082 # Target service URL
          predicates:
            - Path=/reservations/** # Incoming URL pattern
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




#eureka.client.serviceUrl.defaultZone: http://{eureka-host}:{port}/eureka/