server:
  port: 8082
spring:
  application:
    name: reservation-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: reservation-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka